version: '3.4'

# Services definition for building & deploying

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}-app:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app_python_prod
      args:
        PORT: ${PORT:-80}
        STREAMLIT_VERSION: ${STREAMLIT_VERSION:-}
    # Deploy
    environment:
      STREAMLIT_ARGS: ${STREAMLIT_ARGS:-}
    ports:
      # HTTP
      - target: ${PORT:-80}
        published: ${HTTP_PORT:-80}
        protocol: tcp
