version: '3.4'

# Services definition override for development

services:

  app:
    # Build override
    image: ${IMAGES_PREFIX:-app}-app-dev:${DOCKER_TAG:-latest}
    build:
      target: app_python_dev
    # Deploy override
    volumes:
      - ./component/app:/app
    ports:
      # HTTP
      - target: ${FRONTEND_PORT:-8000}
        published: ${HTTP_FRONTEND_PORT:-8000}
        protocol: tcp

  frontend:
    # Build
    image: ${IMAGES_PREFIX:-app}-frontend-dev:${DOCKER_TAG:-latest}
    build:
      context: ./component
      dockerfile: ./Dockerfile
      target: app_node_dev
      args:
        PORT: ${FRONTEND_PORT:-8000}
    # Deploy
    volumes:
      - ./component/app/frontend:/app
      - /app/node_modules # Remove from bind-mount for better performance
    network_mode: service:app
