version: '3.4'

# Services definition override for CI/CD

services:

  app:
    # Build override
    image: ${IMAGES_PREFIX:-app}-cicd:${DOCKER_TAG:-latest}
    build:
      target: app_python_cicd
    # Deploy override
    volumes:
      - ./app/dist:/tmp/dist
