version: '3.4'

# Services definition for building & deploying

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}-app:${DOCKER_TAG:-latest}
    build:
      context: ./component
      dockerfile: ./Dockerfile
      target: app_python_prod
    # Deploy
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
