name: Publish

on:
  # Run on release events on releases (not pre-releases)
  release:
    types:
      - published

# Set GITHUB_TOKEN permissions for the workflow
permissions:
  contents: read
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  # Do not cancel in progress to avoid publishing issues
  cancel-in-progress: false

jobs:

  # Release job
  publish:
    name: Publish version
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Set deployment environment
    environment:
      name: publish

    steps:

    - name: Download release binaries
      uses: robinraju/release-downloader@v1.8
      with:
        tag: ${{ github.event.release.tag_name }}
        out-file-path: ./dist
        tarBall: false
        zipBall: false

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ./dist
